install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: TwNkLux8Px4WCCONyGGA//EWMxJZg/WwiAAbaPqqjTZr47b5f5ZuEDYMbbTR1c40vyiteMqAY6bua68/jtdKgM6momRxWex/z3x5VAlKdIH2VUVO2ttmiskIdpkdhdEh8AX+n9021jk0VAn92R9q0Z/KzhSq0u09QkL96jhvKGFqotI1w2omMelFNgXxfN4Vria4IsuZwVbUMhDVv9eARE9luOlCZj+j4V6X/IomihoCwU3fb+X7+Zfdl/APm3yHkLf0SrzJfzbRTOgDYwqQfUl9lrYkrgOwFU5fRF+MZtzOC8R05Qzm45pfDb9FNtQrjz9LzvNUww3efbUo4IthEuoep/i5IZun9imDWZkmrv5kx5rb12yT+sWtStBPUgw9VjBgyo+AE21frgmjFSbaYEhulh276GdkuAMtCecmsT3Cz+vzMBHsLETPb/z76Cn0FcLMxkd7hyfsvg1H7AAZdYV9lyGnfly98S4RxuQU4/hVCP/VLngnsbcHonwHf+NFWYOTJLJSsA+bvAFuAsxay5auEUgr7RQRATljEFReZZwIB1PjlEquLL9+O3C1B1Sc69clD0ErY+VtIY6c+se2k1I86enKBsEovuue2YVsZ0MC5/4EGjiO5Kyh8lTCyffbIzse0AwCZ+Dqzd3MS/q0m+D3a8Kd1Gh3TZfOcAou/h4=
  app: flaskTaskr
  on:
    repo: yu274151/flasktaskr
