install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: pt3/JRmaP7DNqAEp7mn2cWesUue46F1OCqII6chzETseauNaT9oIQFoXx0LGl4LR8tA3IhdTZoR1VmqOPWeJIUYI92Hwd9QrDKDsrSEhav4gA2RBmYaSdaN9GxGhHKQYA/KpKPh2I9ndnMt6FajAjGl8rkvx0SMQokiOuRhBtfLNV3nlTVvtw+GgsuMyRVTDvsWNhzCXz6AhvvsEeqgO22xrXNOqr8FiPNUtR/wn/jl3sQRtZa8D4M2M1zjW59nKXWDjj0aAGfDKBpvAqGQh8RlkfAg9R9z5ZfrrqfSWgFLnsoewLRsyQcJfB+kOIN/hWFBJaaGgkFxNpQRtwnd2FO990mifFwM2UN1F/3evSWMUT48VwJ7dXxWhjhRHDxbv/EG1/ns2bKAqosS7nH9tHiO5iwvHqYK2LXJUldzjg5p88MMGcQhkrfWGbFH4xH5yMRHCkTUEl6hR51NaUH6m8E5uKL1/lkWkKYTpttg3NYoUIWqFKHXP8Wo4i3A9xiUDrLRrUKhRGVsXWtJH1ZTvUiJ7m2bQF4Q4o+32UBsgDPBBOSS5X0doUprpXu36TPcGv+CGhDpKUYYUUJyXG4tJLM1xs1KW+o8hNI9hRZ6NZ+gsMHq9REdcze3cbRpT9ccB6Q21dhd1vvOkBsL2aBt3L6GerftEczTPl7PKYONxAro=
  app: flaskTaskr
  on:
    repo: yu274151/flasktaskr
