deploy:
  provider: heroku
  api_key:
    secure: xNGxqFJ3u9wUu6F3DlxMG5oIU12bMGEbTmrH9CQK59YCwmhtcdK1YnpTGMFIL8q07jtc1yWgaXEDGU6NBg28QztIHy+qdnAjWwEGcczrZAuF3vJ7kks8AqbsK1F6w8FpWtjy8tz2R+PjXUB3uMgbO5rrCdEETEx5I0H3PMzDlYYCpDW4C5OCIG2MKtmkAlDCwVmF7bnyvOs65TAyovcYZkBDk87CSuQ4fsbYfgFH6JaVajMt7L/19/5VQm53DfBmOKu4MxE7PAoXY9p8G30hkVd9ZMtZR4jD4vivz5hYESY/DvFBdgOKT6cN9nOQjPyf8wqSigxgWNnxDhOogJfj9UEahoQRRjZ0RD+DHti54O7c3doW3qMLXVvtCGgHJqeklty4OajNOxIVOIBZEecEqTA7jGXmcRYEWOg9TSnE/gSkacK4NZvYnh4JL8vKmtfRzmX+d6mN9jubemwYMOombvX/O5jWQvNVQfixvOjOfutyxmOl/ojcbQOhS1J9T6+Vfn7dd44s23WCm2i7P5JtzZCwfaJh3enKskRws9UZ+Ai2UBmn6BDbyNgknIcr8vjS6ctIY85ySO/+GO4D3rYVxt/KllyRcthPGQQXhHU0od4uVvk01tjUbJRUiGlUlroZD/d3BG7IIN5rjYuCw8Vlm7M6AvBTOV1H0APyb7IMyzE=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
