deploy:
  provider: heroku
  api_key:
    secure: TPeBfnq5+VvGUxZmwEb6cwIIK/O8e01yKbEZVicJw2dJYLfsQslSNwMctTabfjHFLy161RgbNsqh6tr5ZXyG88NHfCepksXw69e6FeDTIhB/CKzGAHv6Q79e5AfxGdIOS358stAVDnU+LmJ1+xtOyf+SElKojrUcYrcU4xBnWfVA+23x7SgF36ckk0QRwgF5dLKsFLpObchhMXwB78vzgNE97gH7yBjwShvU6itydMLxjXIlfsnsk0h/oBZvwvR/6wXRKjfUogyecxLJwq8gS4uVN03lcbxVvQSCgh/sBEOkMFpbiju2r0RctYSGbZrGNE+6EkIgsJ6ip+FtUezPJrJWdiX5Egi92b61+P2tjGmu0NePK4gDCMCuwLgZ3Jt7Q68gjzU2jVzk+A7wxs24iuLtVcH+ADH3FuPHVj6zCEhWVtCxBJNZf50paNRDcYshpeeyv9OHXchr1ctKaYTGtfBuGq7RIdEJBpp3mESUwr6XRRFsTL19/BRBZkL45Y22pHJ/AmSP9TP8SF4KHzuchKjWzSfrcnME4lAcdaeVf+y8yLIhVRIoFUSKAlE33etWy9g1XsXOUIWJcGRdYh8mve5j8k3/SPxL5/CgEyUhHQwR+wEqRUMREVpSajb0+GEyMX3CCuNaa+r9uLjVsNP7OdEqK0aUYgtP2eNTfJibvnQ=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
after_script:
- git add project/test.db
- git commit -m "fixing head"
