install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: w1WF/0CiEjgXF3ulBWZ0HZHFYuzjiwVMKoruScZ79zC93dsLjuo7sWVYGZip8a99ej+5bdZeQNlzTHk49NPP2S9MoXvCT/383de+8cpwN9hrYPr2uQu/smqmFZnoZa2JAHE9XSy8baGefPdTLHSfzTazEtE3VTU45YOXb1WzaC3DJhggMsiWBi5LE3NCxcOzVJaYV6XHpKjynIs3anUjJLWJSM4AfQXPqERfmL5xylGF1/xLLBsGhIQeIFAeYttPzLmq2LU5YYDUQASjRwI617GIWUsbD0eMknE1GwDUPYarCg5NlRyaSD+WaIn3QoSbfrG3l50FOmk2Uih8UwaAPoKefb/+TtliFSR6HTb3AB1hyss3+LQKqSTmniGbTOtb+mLpnrLahjOrPTpr9ENs+SXEPBZeKKPDEeFdj6+SUQrblydE7GMclvpI1ahGB5kdg1FEy8kIMAR8KLL0zNh9/MWquBWZE5NXh+REM92hnmNcrkXw5oGiDNkGYHdCLW3Z5hNEh/fa+GWS72VAmmVULXOPuY1jspOqXoWqIplcMYgsLDIkMGZ0ZFxal/pNu3liAuSCUMOWb7WXz906ovX7ZGR732jo9Lw0I4g/86AG8d9Ev4fVgOAyTRH3cBgKXI6uPx1QpsPArD06zQ38DYaOZCdCjPVm7e8c2nsBnsW0zZQ=
  app: flasktaskr
  on:
    repo: yu274151/flasktaskr
