install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: uuwF0D6YWy56CE+9uKE3+7GtrEd7mKbrjs6Pk5f0wxafFQrTLIrwvxFvocHCamhyT26t6v6TKUj5fsJxUDrr1kcxH2igxLkOFzVW4GLNZ+bl6VnjaoyqiSyxmYyXZYVawEQS7pK4H9PdnAVUb2aooaHDFd9lwW0z1hdlYu3dgL0xCXq/cia4RPxbuiShXpBZf3cKWIMTsoeVp/3UPIPdkJvXIucrBMGu9mGYbIS0s6sFhJ8drvSchUl+1bZHpZxQCQW2mlETVN9znH2auwpWMq/jZwtGCIS68awGdsXCL1brPya2MPznXFkDfjp9BLnTtlaFnBGrsWnJBmRPDjUOuzPgElhT39TMWPgBHR4Ra1mLJiBkSEWl6IEKKkPDHgYNJfinrhi6QIATr6BWlomVaHuxtmKgZhtpsn5DTYB4lKY2WgfwUU6ZM3Ioo+nv+MzY0Lp/oaVnZ9f7/JsHxuUDzhp/84C6tqPmy9iomGKEg7ODs47h2wiMMZzqCEP9kulX73uhAQcvXl6677drNHtSs/2v2CGh0/sE/6yftdBOdeGsgxOG/kby0EvZvq/uMAIeoWWePHmK0EIQkEN9huAtwieJE4SQ8SThT5aUVV12gaTTCZudvkCW882szGyI0tYrACP9RwZCPy2myVV1teHud+CaE9KI+kfi71oJIu3670s=
  app: pacific-oasis-17750
