install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key: 6c49fc45-4203-4da8-8178-8b05559ce800
  app: 'yes'
  on:
    repo: yu274151/flasktaskr
