deploy:
  provider: heroku
  api_key:
    secure: JWgTJ1AfOV/MRAbiJ5ByZeif96/8+EF1YVDSSW1vl4JDsKzp51/nR8tOpw6vo7jFBMYNj0BmhTp8Qh6FDptFE4TgjUP2gzb6ViWgwyci9GKgsD12YEUO1nGWozrR0JDGMLcKb4gUjpVNyK4/yXU77Zyun/JqMpbolLumj5wxxXzgrwJ7TcdWjb5rybWXcgDapt2kEmJJCXjP863FvzCjYolqHkk3DmaDEu6079FTA2heji6sAF68HvwO0PnA7DUIoJwm8T0jiw5LV1vbXg981VsGi23K5uDxFX+1xKLuuy0JnjmaX3hhvgYHFz3F5Brk8y6c0KOEd3C+Kyl9jUXAGOdOYF+8005z94ciitgIOW+kGfdkI1TCLkYGJt11vhubmXSQAvCgpVURrJfiZjMfkhjS+009E4gfjZjaI2yJ8yO4VPRkKoF4DBeSfhWUO052PjzoY2DaEpVPlbOVLXPffuGnSUEKHUm3jERRTD7hven/VkJd/xPZhZpoE9NsDZ3/o7rD7sh+zRvYfh8FaSoPwqxEFvjTN5ZOugNOzOeY61DKQCFVvIElSM1/k6agpE7hrPhNrNc8wLW+RkFcbdduVBbGEvUvVdQKEO3Vf6LbEepx9moV9jIWxB4i9/7RjajshV9sIrPJ9SWTJw8PfpH1aok4oBAs7N0CGYUa6EsjVzs=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
after_script:
- git checkout -- test.db
- git commit -m "fixing head"
