deploy:
  provider: heroku
  api_key:
    secure: TCorLvmgS7IFMsGj3TVRllhV5YgLKW3JDgGc/4r0b47QEs7hent29PpzVgEf+5uFghepfZPZ8kEnCcZmonQUXsnXi0aYdbfI+lW8PPEJ40bCF9tqipvjr414fvHulJFCjaW2BVL/UJHPleCmKxcR7GBxzNPAdgEayjd952+1A4tBtQlFKY+oqFriYzWzebKlmd3JZSiQyC9I/MBPc0o5V6tlzri8SWxmuuplAJOXu12AZBo7btC+LkprXMLHJOh14YSvJ2MAZX4qzN1mWU+ywNUz9aOlOWCCUcpyYFiREujIs1qygQ9PtNbPc7+KnpV4t/r3z96RTPb5B9TMUfhFNe0Z1FYBAaiXaf0lv7NWT8pmhU4zOUOHLUE7Ni4kaOnpEXd/l3rhYIEw4cEOrP8rPOFdYu2tSLGrTC8WxkRmKfqk4XOLWiFQXqZQMnwQ1PX7uEUykI0p1oGOM5X2jSuUtCIHAeDzwf1e5nW/gSMH0qKKAllQ3tG3UPqYzgMVY+r8KkhLeOLnuoucxv/g4uaGiX+w8ML4dSDe/C0Opoul5UU8n5it+yliFxCTRDBbYSdpWmnjJTqqoW9UZSKchmUgKMEXzji96OvH8ZX5AbMoSjQr1q4vakRaomuzNBCiF2m/w1ud3V6s9SBQOGpupqqh3xBrAogaVRbHo45UtLN/ha0=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
before_install:
- git add project/test.db
- git commit -m "fixing head"
