deploy:
  provider: heroku
  api_key:
    secure: PnYrJQKG/6r3M0WdiqcPorkreTNIR1yEh2qKCZBZBe3axwhY1vYiDuNknRJeiJBnnuxwhtHGlwzwOv59eJ9vJMEL4CT2h1/zXJlCDRLVtRjqT4pj5GJ915nNd9CE6QcYGxRrJJO1oWCL6oZ7z7tiy543iHALq+1ubxS5wtSrkASKFSzZhBaY3CpNRBN1sluQLYY+W12vumDQtu+URbp/wJJ8hdoGEeIoU6lUe7KIYOL1zEvJZ0BB//m0t/JW+bBKGkXw4kq9sKVDGqDJ4Nvkpw6AApt2amFu/EVlGKq/SySpuQ1kjTur8ZiUeuv07qkEHx1mk8dOI+tjvFLLjaS0XLS2TxBQyOiF9aSElsVv9n8g9QmVg/TuVef7z4AAn7XMB+CkfSJ0wphUHGNCv74SFMML7B0lcX+ndjl/voJ+9OuUiT0E0jqLnVxrMGKcSlNfH5nQX6ZG3nW7q7GKLmGMxLCKdYGBAgIbwXZ3DWxSF9FskFmzWmAEA7r/Lx+XlXhE9b7+oC5wo8/AXbCJSr330fqUhbUEyQlC9xmsNVSuaBBS1xPVdc9zGEVnj2Hix/8bvbdKPnsvJ7/apPmfxFVEB4e6jSJranbCm0/0UuY+D2OEyJwgi9AE+eWasCIROGCh9ppl2ur1Szt8wOAOjV4OHB27fO8gnynqet+9ArTnuUY=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
after_install:
- git checkout -- project/test.db
- git commit -am "fixing head"
