deploy:
  provider: heroku
  api_key:
    secure: Q4xj8a1JmmZgQy9pXqBXcPxgbZD2pJiDJOEeqd91MjY2ZCQUJZQaXqZVQCi9ggQQR4IFleJugHFq9l2YOZEU9PQXixF+YHwMy7aaXDJjQtaBrR9T0yYM3Q8s+tlla2irpk7WZF9sNpsZCBsoshnZZwBpMdPt+tXtiPuLH2F4vh7AOAUiCEipDL7VDrbJcHq/TPQTcWeLmtOgpk4HLTYJ8+4eGTBEFgjSwhGKmqTJXSr261fG6H33oNBDwewd3uN2urnjtm/5ADouaoOHNHJrE0chgy3OIMFjU4AlmPua2Y06/+1nujqlOcn67YV2GuyuL5N5z08YnKjK+iKG/C7+TfaAx7wtj0Xy3VT0mEBr+qx000v2mdWH+mUdHqWeF3p7MfwExDfk/X/PJcgM6V5dj3S039Hw5sO/EP0F0hPvr5KxTnz946kj8fM2NAEIKveY4Y/DTVaBbDBiO59PRFEboKEQ5xE15litw6RXH6i1ECANK02IcpR82uwDp92XlGMsx7L8XA1/XuIHTv9ytoOLpD6Lk1+4pF7WKLyGJG7UJF0LJfjtCru5gza5oyoqlUBgRf68KhjcKZp2i7BMTfQkezKYCgveFr/cWYza+XkL29pQr2zDhoTjJ4ychkK5PaNaiHXYkvWOOywj9nsVOJhdqzUQnEHVBQpUcH8ohtFwXuQ=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
after_install:
- git add project/test.db
- git commit -am "final"
- git checkout
