install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: ZvfiMQpB7j1myZwxTkC5zI6XE8DU7HI0rzw/MJtCoKhqza90bPFtQuKk/MDN2i8HITiTMZyf9g+NZrGdC4e519UBlYONfBVjz5BlFyiRkxQ58ZaUMVpO5JrAuGKLbqWYwe1F1ly35Jv6VQo0c3Y8oJVfmhtF7VB0NUYbwmQwcQgDcUrBPn6ixlbQxg8FuVHLiVlCAmc+7rUmUd3ntYa18dJTozwImKp/vBJQ3Xr8goYRjkh56QymBS1r+BLkn69dZLPdpZwfzsbLd8lgeDASXAINR867DgmQvyKFtm6/I0Ik7rbbVy2pM/BNe5wEH0sd/GRKb7oDJTiEjtZGUDuSXxDWcoWn2f+5sJlDBtpbMwKWT6fxj61gQVpfFFDoC5whbeVy+DvYSSiKDfsTe6LE0UhKVMAibTDtyCb1VGAPwUtYIgl84Dq7ub7ot+l4Uicqe3gIFu4c/f6XAV4m4OiUutQ8aWYl4nrT4l30FuoydaIrkRfHadOjQryE5mO+APF3NHq92+LkwZZRrWtah2ysekJgCZer9dtpNqtx3LpUr0nmaLQSCrEMJG2gLOT3eBJF8yqcnlsiooEuPBBelfJlaF1Ve/Sf28ZJp+mHWz/c+60CVfeD8d2fv5py70sbwdz2YrSwT1E8mkU3vQcmkys48y5MK7k4VdHmvjSWL11rY3k=
  app: 'yes'
  on:
    repo: yu274151/flasktaskr
