deploy:
  provider: heroku
  api_key:
    secure: erRf7J5ooGAz3i6ca2Y/DOPs1xFpnAAPPfhovwmt2TALArU8+TdqC25I2lWddkKN/U+ATvH4J/71ceL0DSXcrhBblYxOsKu+0FbsaSMm4m0Ir2bZA+jmctEWBBAikD/42K6PfWu4qWAYxBgSj57fOHm1hIgpgtoYBK2gvEaBdkxK2aQUnJluRFelmSrYW9SBscZcwzjvXCorKY0L1HK0l80i1vsRXwBJJdSS5E258GobNOQxgln3sS/1HGIdvAIiKavOVexig0ZRtWwhg9zesUSXmGIRgFl7SW+L3dOGFFpGxR/+V7FTAdtfVCvJD7MTfGNLJmGnKkXa3BiaOzaZbSLZ336d/WnU8TjVMkmCz//1JrS3aRPZ+SoN8l0UWNZopzLbGyaWLMBQIQJYjsxUc8sZofh9YZdr1gMNVS5H9ya7ASIWyekieVSgbZ7ycwmiZU9mOXVS6wcikJdA619Ik2KAVm/UW3eidgII2y6iWgObwCGsEVlAnThr2qmWSblySqVGSyr3XYDoxDkKCnFXYRjEAXGXHCMtMyAcoVDhbTMaiUc/+dO4RdOi9RsV1dqUbuhSlG4kaeNwMOR6R8BnxZ5Wb3mA3h1nQQ8cV6jomuJc3Ws8PunoYkk31LIEqyWQSVtzI6IWFap8FpSPltEprC+eoY17TKqEZLGe8XY6urg=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
after_install:
- git add .
- git checkout
- git commit -am "final"
- git
