install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: PTrO0TfDEixw23MWE9Z1XxhTFf7QdUWmx5mfcpaC8zypT3WlS9RmZs/6DlzmDKfXoZOB6ivxKSyALundf78XnSVGBBCyPxJ2wowirxTnDogNxlmhOaoIcSNtcyBWjkZzkuZ17a1jEaJjgNza2kQXBZva6ALyC5vkwM9E0G8GBOYkanvd1yrqtJxUKXTVI0m2kMEd95S3vOoPIzwCZ4cwdyQjasgmrGJi8WcVLVd7NFu6YsmDixcGvuxYcu/mSaoWXBUUdXu7mJPvuwqY/i5RKJefe7ZSgmg9TX4B3BX3si50ElBPQtXmenXAMew4FN84u9qMiLMzIU+Poa/kPpszYDnhFK7hM4ehWme8l+1y+u0D4LR4HEY7ZElFu+nfTu6fbIUZqsKZxitY3Ko6jn+fwjFKwcA85Kk1Oj/btaXBmRl5oUZVsjpPJTbhNTdOY7n+pZFsyLmHvF+42KAzs3xUf7NFxHPYE/bxHA50dweE1rcxJTw1rDHS2Z7smatFq7cizThAEdSQYocP+IrdaTvNYcBvB0zLXL5lI+zj2/RM8GcSXpoIaQupbHlVuklDYqNL6yyDssX+DlJ/K1+j0S0z08FaA1UchWMrW8MwDQvJAX2ouvcXIYnbkLkugaLSRLm9q4A4gwORmXPbGlVWBIc/34w7/hTcHeakJxrgg2ZLvf4=
  app: flaskTaskr
  on:
    repo: yu274151/flasktaskr
