deploy:
  provider: heroku
  api_key:
    secure: DyIzzlaTJILf/hTgU3pwr25W7FArFdxoOBXw6gh7E1dF9aAWGi+U0wWNtZQlxBpo5pbBOjZKmXHvjxXGkkHbFqqA6OHJcZMeClmJn3Fn89nbRCQi3d/lQ6SbVxkOQ97Nd9eWxZtSMiEaQhf3qskCZXGtKFoly0Q7KU0wMFXXLboOyXWCXrBhjcJX4HC7YHIt04MY18Pvow5ePZ5WopU/OcWLdlIQVDA3IkXhf+R+gQ+peO/ETSXv/N/ernshVJen6xCT02NJaRe4wsca2a4kaLg82O6eRyXigrYuzYJbuka7rUDB2aEq64gvISNSxqhPkZEeKNoRCAqa+zqKH0WD/NMqJxg9jumOEgzYvFqgMP54AWqMZBIUhgMT3qaGc6I6qYJf+ssTX8H6YdkSy+N8/1bkBGgsAqTBsugs/fGah1YOGMbIRjDh0oqq/Sy7PPo3VccfSJ9goatMR7hjjY2+An1E86zZ4lD0lA+TSnDnDcd6IDUXCAS2FMtWXOkhflY/ajOE3MyIs9RoExs+KmabwAPy/CZdSvcSOuakwS/Os0fkIR+2GepCTZDYfVKFsFNo22cL4iK3/+Yru/ZffplqG6GHPP+Wy6pnOAE36DbjQrO4l3R+SnTkykMGYiZxL2hVVUgGoS+EOE2vnFcD1mPQL/uzaPUrSQQsepi9kwD7yRk=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
before_install:
- git checkout --file project/test.db
