install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: JYCUIacZ0pCIbclprOrL+JffsSG9NSTMSqp/YKfkeKNndMisl1vCpKhSTXVxrobh+b7qHvQ1nFb7ZptA2TW2AjqGTIsOQUMWBAYEUh+PJoEf2YBSwrsfkLFBN/7ZR7eITGefYU2DFeNSLTT+oeMo5hW1Qr9zfZ1x72Dvb9TLaJL2nDs0a6n4/ibR58BSLuFWveM971GMZ6VSidyuJZMZIvrV1mQO81lXV2lC4cpNgDv49Lz8w8146xB+3sm0cSLiKhp3CCJqJ01tFNTuyypvRSJSIXEUMURF33JOPNzpf1LP1kdt4cNByHdBrqQHTdiSxQEW9nGZRNVsO4H4WVnK4CCDDNfIquFuYBx0xqji1AuD0ZQhKyxwRxMKp7ZrErdNtsXjuJCFBLI+ThCgIT6MdiL4qEzS3XydvO4b3SUim6cfVI54g2LAEeIm5xIN5fLYWI0nQxO9gTEWv22to53kss4R/3si5oOl8CwtsSRdqb4w8Nx9ZbtmmMrJdp3uzxRcu28BjNo3pViHgmeGgDwyYrokR4SloFu8SMo6gymGDk6REEGvODD8awGA1USZxY0FD1ZGtCn4e+ab7SVUoWr9SOZJmmY/Xg/6rmzSM/ynT+EKmXN65LRGmS5THyKCMCdDaEIB/RsTRiKuOpMEPYKjrSvdjM6SCnWjzjTkc2UTRhI=
  app: flaskTaskr
  on:
    repo: yu274151/flasktaskr
