install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
deploy:
  provider: heroku
  api_key:
    secure: WYjW2LsFmU6IJKQI5WvRTqfQc/rS3z5wnlglXelsPVHWUEhjY8PTReynBd0miuJKrGx/YJJS4yZ/yywQXblsQs9Nabf8MinqKlgDasXoEC2r6VQs5N3ABQA4JOdbW5IZwClS0Qr8w8ii6a4ChRdfvW7i8H6Zp+LKaLaok15tDUzhQKUW9FTCfvv5B6cGfJ1ZNvsh1TTAw6JkWUC6ia1QnpZwWmHDR8cqN+ySnjNYTwfhfHsGho7ISLVn85PnSQPwtnXIxROg+mwg5vESBlNpueXtA6LzWnAOK1JR7AQaygpGiK+PBVT77ltjjS6GVE34aSHRl5eEqna1tB6KNItjMQLAuGEi4qPiF3OwNGp/FnNzyqP7EjmBWBft/SWUKbofrL51PQlMps/pmZtgmIyUibYz8HgGVUo+wTNNbdR5sbanAeJtkwfJQfZrAwhOeudgqGlfoCAgrSHp71MSjkPIanXLCnNorHXWYJQL5HwNmjRiDdPQUtY3DiaBTGLsj2f69BZ0NqA/ZF1h9zgTWyUn6EFW/JeDrbroc8Sdg2q/QOoHj7UkM+F/2i61v2Gq5rlTkl8x6DjcfgzehnKdrO0ikkI74G1J9t/esyIZ5ftcvO24mc4TG65Mlyhv35L3JmajnYqUBeVWOkp0KABBzRfdpeXhryUM9Z39sXW/SwcqNs4=
  app: flasktaskr
  on:
    repo: yu274151/flasktaskr
