deploy:
  provider: heroku
  api_key:
    secure: E3VemwXzMMiFiBRpQNUVkfGPWz5BNUPDC0H5Pq5wq3eoPxkRRu8KcNcNbUnCj0lHyexD6d+m4XXAEzfx0U0WBCZWjk1D+CEPHqQRO4MSXIdTVys0h7qo8tt7Ov7ji4WrMBNq0IsGoObG3V5g6HXC/qMMSQJb8DOGtSla3npQn4tBSQe9sTu3uFyxS4f8xQ0KWc3dV4N+BZBCNwFd7J+z2RnUPXO9ijXPJw8NbuI0jNjCwwCsP//raFQ6Z/WLm4BrF0wXTKEY+iHBHMa7LYtQsIHMRleGPs8uvKUm949MsPH3mA66qtIBlSyquXQlyD+0V2lhCU6jCnSC5g9GxzBk02VoWALwLOGsyYPgA0FleKQP162wIWsPoazMgG+9tst8OWwS3ojFbdJQVa4ihaHEjTPbW09WBykC9B6ofJYoie3kJ/gFz/8S3HY7bMeIWqYlzrzOxYi+0feH2YSe/xKEPgnccM5P5aq06srC3K4hnD1gv35I4Ds5TmJ/c3GTe+ExEXC0mnN6yQa53uagfIjixP1OBgSNSJbVqt4r0om/cFPOuGiIDw2bI/nBjaEJrnE72JDvl7KqQmUCgucRPCSm+kj4rGQgJLjiN2Yhe2Zu6hcSk7+MRmG4iyWPc5euzdCmzZTJx5VPZ0lw+URI9J4jVlepsk0F7E08LIR/s4BS7vI=
  app: pacific-oasis-17750
  on:
    repo: yu274151/flasktaskr
install:
- pip install -r requirements.txt
language:
- python
python:
- '3.6'
- '2.7'
script:
- nosetests
travis:
- setup
after_install:
- git add project/test.db
- git commit -m "fixing head"
